// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: improbable/entity_state.proto

#ifndef PROTOBUF_improbable_2fentity_5fstate_2eproto__INCLUDED
#define PROTOBUF_improbable_2fentity_5fstate_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include <google/protobuf/descriptor.pb.h>
// @@protoc_insertion_point(includes)

namespace schema {
namespace improbable {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_improbable_2fentity_5fstate_2eproto();
void protobuf_AssignDesc_improbable_2fentity_5fstate_2eproto();
void protobuf_ShutdownFile_improbable_2fentity_5fstate_2eproto();

class ComponentInfo;
class EntityCommand;
class EntityComponentUpdate;
class EntityEvent;
class EntityState;

// ===================================================================

class EntityState : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:schema.improbable.EntityState) */ {
 public:
  EntityState();
  virtual ~EntityState();

  EntityState(const EntityState& from);

  inline EntityState& operator=(const EntityState& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const EntityState& default_instance();

  void Swap(EntityState* other);

  // implements Message ----------------------------------------------

  inline EntityState* New() const { return New(NULL); }

  EntityState* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const EntityState& from);
  void MergeFrom(const EntityState& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(EntityState* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  GOOGLE_PROTOBUF_EXTENSION_ACCESSORS(EntityState)
  // @@protoc_insertion_point(class_scope:schema.improbable.EntityState)
 private:

  ::google::protobuf::internal::ExtensionSet _extensions_;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_improbable_2fentity_5fstate_2eproto();
  friend void protobuf_AssignDesc_improbable_2fentity_5fstate_2eproto();
  friend void protobuf_ShutdownFile_improbable_2fentity_5fstate_2eproto();

  void InitAsDefaultInstance();
  static EntityState* default_instance_;
};
// -------------------------------------------------------------------

class EntityEvent : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:schema.improbable.EntityEvent) */ {
 public:
  EntityEvent();
  virtual ~EntityEvent();

  EntityEvent(const EntityEvent& from);

  inline EntityEvent& operator=(const EntityEvent& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const EntityEvent& default_instance();

  void Swap(EntityEvent* other);

  // implements Message ----------------------------------------------

  inline EntityEvent* New() const { return New(NULL); }

  EntityEvent* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const EntityEvent& from);
  void MergeFrom(const EntityEvent& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(EntityEvent* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  GOOGLE_PROTOBUF_EXTENSION_ACCESSORS(EntityEvent)
  // @@protoc_insertion_point(class_scope:schema.improbable.EntityEvent)
 private:

  ::google::protobuf::internal::ExtensionSet _extensions_;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_improbable_2fentity_5fstate_2eproto();
  friend void protobuf_AssignDesc_improbable_2fentity_5fstate_2eproto();
  friend void protobuf_ShutdownFile_improbable_2fentity_5fstate_2eproto();

  void InitAsDefaultInstance();
  static EntityEvent* default_instance_;
};
// -------------------------------------------------------------------

class EntityCommand : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:schema.improbable.EntityCommand) */ {
 public:
  EntityCommand();
  virtual ~EntityCommand();

  EntityCommand(const EntityCommand& from);

  inline EntityCommand& operator=(const EntityCommand& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const EntityCommand& default_instance();

  void Swap(EntityCommand* other);

  // implements Message ----------------------------------------------

  inline EntityCommand* New() const { return New(NULL); }

  EntityCommand* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const EntityCommand& from);
  void MergeFrom(const EntityCommand& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(EntityCommand* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  GOOGLE_PROTOBUF_EXTENSION_ACCESSORS(EntityCommand)
  // @@protoc_insertion_point(class_scope:schema.improbable.EntityCommand)
 private:

  ::google::protobuf::internal::ExtensionSet _extensions_;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_improbable_2fentity_5fstate_2eproto();
  friend void protobuf_AssignDesc_improbable_2fentity_5fstate_2eproto();
  friend void protobuf_ShutdownFile_improbable_2fentity_5fstate_2eproto();

  void InitAsDefaultInstance();
  static EntityCommand* default_instance_;
};
// -------------------------------------------------------------------

class EntityComponentUpdate : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:schema.improbable.EntityComponentUpdate) */ {
 public:
  EntityComponentUpdate();
  virtual ~EntityComponentUpdate();

  EntityComponentUpdate(const EntityComponentUpdate& from);

  inline EntityComponentUpdate& operator=(const EntityComponentUpdate& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const EntityComponentUpdate& default_instance();

  void Swap(EntityComponentUpdate* other);

  // implements Message ----------------------------------------------

  inline EntityComponentUpdate* New() const { return New(NULL); }

  EntityComponentUpdate* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const EntityComponentUpdate& from);
  void MergeFrom(const EntityComponentUpdate& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(EntityComponentUpdate* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated uint32 fields_to_clear = 1;
  int fields_to_clear_size() const;
  void clear_fields_to_clear();
  static const int kFieldsToClearFieldNumber = 1;
  ::google::protobuf::uint32 fields_to_clear(int index) const;
  void set_fields_to_clear(int index, ::google::protobuf::uint32 value);
  void add_fields_to_clear(::google::protobuf::uint32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      fields_to_clear() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_fields_to_clear();

  // optional .schema.improbable.EntityState entity_state = 2;
  bool has_entity_state() const;
  void clear_entity_state();
  static const int kEntityStateFieldNumber = 2;
  const ::schema::improbable::EntityState& entity_state() const;
  ::schema::improbable::EntityState* mutable_entity_state();
  ::schema::improbable::EntityState* release_entity_state();
  void set_allocated_entity_state(::schema::improbable::EntityState* entity_state);

  // optional .schema.improbable.EntityEvent entity_event = 3;
  bool has_entity_event() const;
  void clear_entity_event();
  static const int kEntityEventFieldNumber = 3;
  const ::schema::improbable::EntityEvent& entity_event() const;
  ::schema::improbable::EntityEvent* mutable_entity_event();
  ::schema::improbable::EntityEvent* release_entity_event();
  void set_allocated_entity_event(::schema::improbable::EntityEvent* entity_event);

  // @@protoc_insertion_point(class_scope:schema.improbable.EntityComponentUpdate)
 private:
  inline void set_has_entity_state();
  inline void clear_has_entity_state();
  inline void set_has_entity_event();
  inline void clear_has_entity_event();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > fields_to_clear_;
  ::schema::improbable::EntityState* entity_state_;
  ::schema::improbable::EntityEvent* entity_event_;
  friend void  protobuf_AddDesc_improbable_2fentity_5fstate_2eproto();
  friend void protobuf_AssignDesc_improbable_2fentity_5fstate_2eproto();
  friend void protobuf_ShutdownFile_improbable_2fentity_5fstate_2eproto();

  void InitAsDefaultInstance();
  static EntityComponentUpdate* default_instance_;
};
// -------------------------------------------------------------------

class ComponentInfo : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:schema.improbable.ComponentInfo) */ {
 public:
  ComponentInfo();
  virtual ~ComponentInfo();

  ComponentInfo(const ComponentInfo& from);

  inline ComponentInfo& operator=(const ComponentInfo& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ComponentInfo& default_instance();

  void Swap(ComponentInfo* other);

  // implements Message ----------------------------------------------

  inline ComponentInfo* New() const { return New(NULL); }

  ComponentInfo* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ComponentInfo& from);
  void MergeFrom(const ComponentInfo& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ComponentInfo* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string component_name = 1;
  bool has_component_name() const;
  void clear_component_name();
  static const int kComponentNameFieldNumber = 1;
  const ::std::string& component_name() const;
  void set_component_name(const ::std::string& value);
  void set_component_name(const char* value);
  void set_component_name(const char* value, size_t size);
  ::std::string* mutable_component_name();
  ::std::string* release_component_name();
  void set_allocated_component_name(::std::string* component_name);

  // optional uint32 component_id = 2;
  bool has_component_id() const;
  void clear_component_id();
  static const int kComponentIdFieldNumber = 2;
  ::google::protobuf::uint32 component_id() const;
  void set_component_id(::google::protobuf::uint32 value);

  // optional bool queryable = 3 [default = true];
  bool has_queryable() const;
  void clear_queryable();
  static const int kQueryableFieldNumber = 3;
  bool queryable() const;
  void set_queryable(bool value);

  // optional bool synchronized = 4 [default = true];
  bool has_synchronized() const;
  void clear_synchronized();
  static const int kSynchronizedFieldNumber = 4;
  bool synchronized() const;
  void set_synchronized(bool value);

  // @@protoc_insertion_point(class_scope:schema.improbable.ComponentInfo)
 private:
  inline void set_has_component_name();
  inline void clear_has_component_name();
  inline void set_has_component_id();
  inline void clear_has_component_id();
  inline void set_has_queryable();
  inline void clear_has_queryable();
  inline void set_has_synchronized();
  inline void clear_has_synchronized();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr component_name_;
  ::google::protobuf::uint32 component_id_;
  bool queryable_;
  bool synchronized_;
  friend void  protobuf_AddDesc_improbable_2fentity_5fstate_2eproto();
  friend void protobuf_AssignDesc_improbable_2fentity_5fstate_2eproto();
  friend void protobuf_ShutdownFile_improbable_2fentity_5fstate_2eproto();

  void InitAsDefaultInstance();
  static ComponentInfo* default_instance_;
};
// ===================================================================

static const int kSchemalangFieldNameFieldNumber = 51000;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  schemalang_field_name;
static const int kSchemalangEnumValueNameFieldNumber = 51000;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::EnumValueOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  schemalang_enum_value_name;
static const int kComponentInfoFieldNumber = 51000;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::google::protobuf::internal::MessageTypeTraits< ::schema::improbable::ComponentInfo >, 11, false >
  component_info;
static const int kEntityPositionFieldNumber = 51002;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  entity_position;
static const int kOptionFieldNumber = 51004;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  option;
static const int kEntityIdFieldNumber = 51005;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  entity_id;
static const int kEntityIdKeyFieldNumber = 51006;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  entity_id_key;
static const int kEntityIdValueFieldNumber = 51007;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  entity_id_value;

// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// EntityState

// -------------------------------------------------------------------

// EntityEvent

// -------------------------------------------------------------------

// EntityCommand

// -------------------------------------------------------------------

// EntityComponentUpdate

// repeated uint32 fields_to_clear = 1;
inline int EntityComponentUpdate::fields_to_clear_size() const {
  return fields_to_clear_.size();
}
inline void EntityComponentUpdate::clear_fields_to_clear() {
  fields_to_clear_.Clear();
}
inline ::google::protobuf::uint32 EntityComponentUpdate::fields_to_clear(int index) const {
  // @@protoc_insertion_point(field_get:schema.improbable.EntityComponentUpdate.fields_to_clear)
  return fields_to_clear_.Get(index);
}
inline void EntityComponentUpdate::set_fields_to_clear(int index, ::google::protobuf::uint32 value) {
  fields_to_clear_.Set(index, value);
  // @@protoc_insertion_point(field_set:schema.improbable.EntityComponentUpdate.fields_to_clear)
}
inline void EntityComponentUpdate::add_fields_to_clear(::google::protobuf::uint32 value) {
  fields_to_clear_.Add(value);
  // @@protoc_insertion_point(field_add:schema.improbable.EntityComponentUpdate.fields_to_clear)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
EntityComponentUpdate::fields_to_clear() const {
  // @@protoc_insertion_point(field_list:schema.improbable.EntityComponentUpdate.fields_to_clear)
  return fields_to_clear_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
EntityComponentUpdate::mutable_fields_to_clear() {
  // @@protoc_insertion_point(field_mutable_list:schema.improbable.EntityComponentUpdate.fields_to_clear)
  return &fields_to_clear_;
}

// optional .schema.improbable.EntityState entity_state = 2;
inline bool EntityComponentUpdate::has_entity_state() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void EntityComponentUpdate::set_has_entity_state() {
  _has_bits_[0] |= 0x00000002u;
}
inline void EntityComponentUpdate::clear_has_entity_state() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void EntityComponentUpdate::clear_entity_state() {
  if (entity_state_ != NULL) entity_state_->::schema::improbable::EntityState::Clear();
  clear_has_entity_state();
}
inline const ::schema::improbable::EntityState& EntityComponentUpdate::entity_state() const {
  // @@protoc_insertion_point(field_get:schema.improbable.EntityComponentUpdate.entity_state)
  return entity_state_ != NULL ? *entity_state_ : *default_instance_->entity_state_;
}
inline ::schema::improbable::EntityState* EntityComponentUpdate::mutable_entity_state() {
  set_has_entity_state();
  if (entity_state_ == NULL) {
    entity_state_ = new ::schema::improbable::EntityState;
  }
  // @@protoc_insertion_point(field_mutable:schema.improbable.EntityComponentUpdate.entity_state)
  return entity_state_;
}
inline ::schema::improbable::EntityState* EntityComponentUpdate::release_entity_state() {
  // @@protoc_insertion_point(field_release:schema.improbable.EntityComponentUpdate.entity_state)
  clear_has_entity_state();
  ::schema::improbable::EntityState* temp = entity_state_;
  entity_state_ = NULL;
  return temp;
}
inline void EntityComponentUpdate::set_allocated_entity_state(::schema::improbable::EntityState* entity_state) {
  delete entity_state_;
  entity_state_ = entity_state;
  if (entity_state) {
    set_has_entity_state();
  } else {
    clear_has_entity_state();
  }
  // @@protoc_insertion_point(field_set_allocated:schema.improbable.EntityComponentUpdate.entity_state)
}

// optional .schema.improbable.EntityEvent entity_event = 3;
inline bool EntityComponentUpdate::has_entity_event() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void EntityComponentUpdate::set_has_entity_event() {
  _has_bits_[0] |= 0x00000004u;
}
inline void EntityComponentUpdate::clear_has_entity_event() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void EntityComponentUpdate::clear_entity_event() {
  if (entity_event_ != NULL) entity_event_->::schema::improbable::EntityEvent::Clear();
  clear_has_entity_event();
}
inline const ::schema::improbable::EntityEvent& EntityComponentUpdate::entity_event() const {
  // @@protoc_insertion_point(field_get:schema.improbable.EntityComponentUpdate.entity_event)
  return entity_event_ != NULL ? *entity_event_ : *default_instance_->entity_event_;
}
inline ::schema::improbable::EntityEvent* EntityComponentUpdate::mutable_entity_event() {
  set_has_entity_event();
  if (entity_event_ == NULL) {
    entity_event_ = new ::schema::improbable::EntityEvent;
  }
  // @@protoc_insertion_point(field_mutable:schema.improbable.EntityComponentUpdate.entity_event)
  return entity_event_;
}
inline ::schema::improbable::EntityEvent* EntityComponentUpdate::release_entity_event() {
  // @@protoc_insertion_point(field_release:schema.improbable.EntityComponentUpdate.entity_event)
  clear_has_entity_event();
  ::schema::improbable::EntityEvent* temp = entity_event_;
  entity_event_ = NULL;
  return temp;
}
inline void EntityComponentUpdate::set_allocated_entity_event(::schema::improbable::EntityEvent* entity_event) {
  delete entity_event_;
  entity_event_ = entity_event;
  if (entity_event) {
    set_has_entity_event();
  } else {
    clear_has_entity_event();
  }
  // @@protoc_insertion_point(field_set_allocated:schema.improbable.EntityComponentUpdate.entity_event)
}

// -------------------------------------------------------------------

// ComponentInfo

// optional string component_name = 1;
inline bool ComponentInfo::has_component_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ComponentInfo::set_has_component_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ComponentInfo::clear_has_component_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ComponentInfo::clear_component_name() {
  component_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_component_name();
}
inline const ::std::string& ComponentInfo::component_name() const {
  // @@protoc_insertion_point(field_get:schema.improbable.ComponentInfo.component_name)
  return component_name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ComponentInfo::set_component_name(const ::std::string& value) {
  set_has_component_name();
  component_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:schema.improbable.ComponentInfo.component_name)
}
inline void ComponentInfo::set_component_name(const char* value) {
  set_has_component_name();
  component_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:schema.improbable.ComponentInfo.component_name)
}
inline void ComponentInfo::set_component_name(const char* value, size_t size) {
  set_has_component_name();
  component_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:schema.improbable.ComponentInfo.component_name)
}
inline ::std::string* ComponentInfo::mutable_component_name() {
  set_has_component_name();
  // @@protoc_insertion_point(field_mutable:schema.improbable.ComponentInfo.component_name)
  return component_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ComponentInfo::release_component_name() {
  // @@protoc_insertion_point(field_release:schema.improbable.ComponentInfo.component_name)
  clear_has_component_name();
  return component_name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ComponentInfo::set_allocated_component_name(::std::string* component_name) {
  if (component_name != NULL) {
    set_has_component_name();
  } else {
    clear_has_component_name();
  }
  component_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), component_name);
  // @@protoc_insertion_point(field_set_allocated:schema.improbable.ComponentInfo.component_name)
}

// optional uint32 component_id = 2;
inline bool ComponentInfo::has_component_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ComponentInfo::set_has_component_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ComponentInfo::clear_has_component_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ComponentInfo::clear_component_id() {
  component_id_ = 0u;
  clear_has_component_id();
}
inline ::google::protobuf::uint32 ComponentInfo::component_id() const {
  // @@protoc_insertion_point(field_get:schema.improbable.ComponentInfo.component_id)
  return component_id_;
}
inline void ComponentInfo::set_component_id(::google::protobuf::uint32 value) {
  set_has_component_id();
  component_id_ = value;
  // @@protoc_insertion_point(field_set:schema.improbable.ComponentInfo.component_id)
}

// optional bool queryable = 3 [default = true];
inline bool ComponentInfo::has_queryable() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void ComponentInfo::set_has_queryable() {
  _has_bits_[0] |= 0x00000004u;
}
inline void ComponentInfo::clear_has_queryable() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void ComponentInfo::clear_queryable() {
  queryable_ = true;
  clear_has_queryable();
}
inline bool ComponentInfo::queryable() const {
  // @@protoc_insertion_point(field_get:schema.improbable.ComponentInfo.queryable)
  return queryable_;
}
inline void ComponentInfo::set_queryable(bool value) {
  set_has_queryable();
  queryable_ = value;
  // @@protoc_insertion_point(field_set:schema.improbable.ComponentInfo.queryable)
}

// optional bool synchronized = 4 [default = true];
inline bool ComponentInfo::has_synchronized() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void ComponentInfo::set_has_synchronized() {
  _has_bits_[0] |= 0x00000008u;
}
inline void ComponentInfo::clear_has_synchronized() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void ComponentInfo::clear_synchronized() {
  synchronized_ = true;
  clear_has_synchronized();
}
inline bool ComponentInfo::synchronized() const {
  // @@protoc_insertion_point(field_get:schema.improbable.ComponentInfo.synchronized)
  return synchronized_;
}
inline void ComponentInfo::set_synchronized(bool value) {
  set_has_synchronized();
  synchronized_ = value;
  // @@protoc_insertion_point(field_set:schema.improbable.ComponentInfo.synchronized)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace improbable
}  // namespace schema

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_improbable_2fentity_5fstate_2eproto__INCLUDED
