// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: improbable/math/coordinates.proto

#ifndef PROTOBUF_improbable_2fmath_2fcoordinates_2eproto__INCLUDED
#define PROTOBUF_improbable_2fmath_2fcoordinates_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace schema {
namespace improbable {
namespace math {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_improbable_2fmath_2fcoordinates_2eproto();
void protobuf_AssignDesc_improbable_2fmath_2fcoordinates_2eproto();
void protobuf_ShutdownFile_improbable_2fmath_2fcoordinates_2eproto();

class Coordinates;

// ===================================================================

class Coordinates : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:schema.improbable.math.Coordinates) */ {
 public:
  Coordinates();
  virtual ~Coordinates();

  Coordinates(const Coordinates& from);

  inline Coordinates& operator=(const Coordinates& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Coordinates& default_instance();

  void Swap(Coordinates* other);

  // implements Message ----------------------------------------------

  inline Coordinates* New() const { return New(NULL); }

  Coordinates* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Coordinates& from);
  void MergeFrom(const Coordinates& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Coordinates* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional double x = 1;
  bool has_x() const;
  void clear_x();
  static const int kXFieldNumber = 1;
  double x() const;
  void set_x(double value);

  // optional double y = 2;
  bool has_y() const;
  void clear_y();
  static const int kYFieldNumber = 2;
  double y() const;
  void set_y(double value);

  // optional double z = 3;
  bool has_z() const;
  void clear_z();
  static const int kZFieldNumber = 3;
  double z() const;
  void set_z(double value);

  // @@protoc_insertion_point(class_scope:schema.improbable.math.Coordinates)
 private:
  inline void set_has_x();
  inline void clear_has_x();
  inline void set_has_y();
  inline void clear_has_y();
  inline void set_has_z();
  inline void clear_has_z();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  double x_;
  double y_;
  double z_;
  friend void  protobuf_AddDesc_improbable_2fmath_2fcoordinates_2eproto();
  friend void protobuf_AssignDesc_improbable_2fmath_2fcoordinates_2eproto();
  friend void protobuf_ShutdownFile_improbable_2fmath_2fcoordinates_2eproto();

  void InitAsDefaultInstance();
  static Coordinates* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// Coordinates

// optional double x = 1;
inline bool Coordinates::has_x() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Coordinates::set_has_x() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Coordinates::clear_has_x() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Coordinates::clear_x() {
  x_ = 0;
  clear_has_x();
}
inline double Coordinates::x() const {
  // @@protoc_insertion_point(field_get:schema.improbable.math.Coordinates.x)
  return x_;
}
inline void Coordinates::set_x(double value) {
  set_has_x();
  x_ = value;
  // @@protoc_insertion_point(field_set:schema.improbable.math.Coordinates.x)
}

// optional double y = 2;
inline bool Coordinates::has_y() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Coordinates::set_has_y() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Coordinates::clear_has_y() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Coordinates::clear_y() {
  y_ = 0;
  clear_has_y();
}
inline double Coordinates::y() const {
  // @@protoc_insertion_point(field_get:schema.improbable.math.Coordinates.y)
  return y_;
}
inline void Coordinates::set_y(double value) {
  set_has_y();
  y_ = value;
  // @@protoc_insertion_point(field_set:schema.improbable.math.Coordinates.y)
}

// optional double z = 3;
inline bool Coordinates::has_z() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Coordinates::set_has_z() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Coordinates::clear_has_z() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Coordinates::clear_z() {
  z_ = 0;
  clear_has_z();
}
inline double Coordinates::z() const {
  // @@protoc_insertion_point(field_get:schema.improbable.math.Coordinates.z)
  return z_;
}
inline void Coordinates::set_z(double value) {
  set_has_z();
  z_ = value;
  // @@protoc_insertion_point(field_set:schema.improbable.math.Coordinates.z)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace math
}  // namespace improbable
}  // namespace schema

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_improbable_2fmath_2fcoordinates_2eproto__INCLUDED
