cc_binary(
    name = "blackbox",
    srcs = ["blackbox.cc"],
    deps = [
        "//tensorflow/core:framework_internal",
        "//tensorflow/core:tensorflow"
    ],
)

cc_library(
    name = "blackbox_lib",
    srcs = ["blackbox.cc"],
    deps = [
        "//tensorflow/core:framework_internal",
        "//tensorflow/core:tensorflow"
    ],
)
